### ISSUE TITLE
Duplicative Lint

### ISSUE THREAD

**Issue by kentrino** [alleyinteractive/sasslint-webpack-plugin#10]
When I use this with [extract-text-webpack-plugin](https://github.com/webpack/extract-text-webpack-plugin), it seems to work twice unnecessarily. I guess some conflict was caused with the plugin.
If I remove extract-text-webpack-plugin, it works fine.

Here is output.

```
./src/css/components/list.scss
  11:7  warning  Nesting depth 3 greater than max of 2  nesting-depth
  15:9  warning  Nesting depth 4 greater than max of 2  nesting-depth

✖ 2 problems (0 errors, 2 warnings)


./src/css/components/list.scss
  11:7  warning  Nesting depth 3 greater than max of 2  nesting-depth
  15:9  warning  Nesting depth 4 greater than max of 2  nesting-depth

✖ 2 problems (0 errors, 2 warnings)
```

Any ideas?
My code is [here](https://github.com/kentrino/es6-react-webpack-sample).

**Comment by jackmarketon** [comment]
Hey @kentrino, This might be caused due to the extract text plugin. Try this config option.

```
module.exports = {
  entry: '...',
  module: {
    // ...
  },
  stats: {
    children: false // This part
  }
}
```

**Comment by kentrino** [comment]
Hi! @jackmarketon 
Thanks for your reply.
I've tried your config option, but it doesn't seem to work.

This hack works for me.
https://github.com/alleyinteractive/sasslint-webpack-plugin/pull/11/commits/2b6149e12124e2a408d15c9ece927d8df4bba1f1

**Comment by jackmarketon** [comment]
@kentrino thanks for bringing this up! I ended up adding tests and stuff for this in PR https://github.com/alleyinteractive/sasslint-webpack-plugin/pull/12

Thanks!
