### ISSUE TITLE
Move print of warnings to the end

### ISSUE THREAD

**Issue by MilosMosovsky** [alleyinteractive/sasslint-webpack-plugin#18]
Hello, i started to use this plugin, but when any warning/error is printed to the console it is printed to the end of webpack stack like this, and i have to scroll 400 lines to the up to see real warnings

<img width="804" alt="screenshot 2016-05-22 01 07 08" src="https://cloud.githubusercontent.com/assets/324488/15451258/a930868e-1fb9-11e6-9c4f-3ac2de78ecaa.png">

I was experimenting with this source

``` javascript
// Hook into the compilation as early as possible, at the seal step
    compilation.plugin('seal', function() {
      // We need to keep the reference to the compilation's scope
      var _this = this;

      // Errors/Warnings are pushed to the compilation's error handling
      // so we can drop out of the processing tree on warn/error
      report.forEach(function(x) {
        if(x.error) {
          _this.errors.unshift(x.file);
        } else {
          _this.warnings.unshift(x.file);
        }
      });
```

and changed `seal` to the `done`  now i get expected result in console 
<img width="603" alt="screenshot 2016-05-22 01 09 21" src="https://cloud.githubusercontent.com/assets/324488/15451259/d8c24e6e-1fb9-11e6-885e-44d8c3579f76.png">

Is there any particular reason to hook into seal step? If not it is possible to change this or open PR with this? Thanks

**Comment by jackmarketon** [comment]
No there is not, you are welcome to submit a PR for this.

**Comment by jackmarketon** [comment]
This has been fixed and deploying shortly here

**Comment by kevincaradant** [comment]
@jackmarketon Hi, I get the same problem to display the real warnings like @MilosMosovsky , is it fix in the last version ? thank you
