### ISSUE TITLE
Cannot find module 'text-table'

### ISSUE THREAD

**Issue by kylesuss** [alleyinteractive/sasslint-webpack-plugin#3]
Hi!

On a fresh install of this package, I get an error when I try to start my webpack dev server.

``` shell
module.js:339
    throw err;
    ^

Error: Cannot find module 'text-table'
```

I think it is because of this require: https://github.com/alleyinteractive/sasslint-webpack-plugin/blob/master/lib/formatter.js#L8

I fixed this problem by adding `text-table` as a dev dependency to my `package.json` manually, but I think you need to add it as a dependency or peer dependency rather than a dev dependency in this repo.

**Comment by jackmarketon** [comment]
@kylesuss thanks for catching this!

I'll get this patched in today.
