### ISSUE TITLE
Upgrade to node-sass 4.5.3 for NodeJS 8 compatibility

### ISSUE THREAD

**Issue by todd-richmond** [alleyinteractive/sasslint-webpack-plugin#30]
Can you please upgrade this project to 4.5.3? Due to the major version jump, using this webpack plugin causes the old 3.13 to be installed as a sub-dependency instead of using the 4.x version. This then fails on NodeJS 8 due to missing node-sass bindings. Node 7 works with either version of node-sass so bumping should be fine (barring compat issues in your code)

I couldn't find a way to force an upgrade in my own package definitions

**Comment by jackmarketon** [comment]
We are no longer maintaining this plugin. We have switched to stylint for all of our projects, sorry.
