### ISSUE TITLE
Unable to make "file" configuration work

### ISSUE THREAD

**Issue by elengart** [alleyinteractive/sasslint-webpack-plugin#4]
I use sasslint-webpack plugin to process '.scss' files in a specific directory, targeted by glob and reading rules from .sass-lint.yml. Works amazingly well - thank you! 
I need to be able to exclude specific files. It appears that, no matter what I write in my .sass-lint.yml for file configuration, for either ignore or include (specific file path, regex, directory), it doesn't have any effect. The issue is very high priority for us because we are planning to include sasslint-webpack-plugin in our automated build.  Please help!

**Comment by jackmarketon** [comment]
Hey @elengart, I'll take a look and see what solutions I can think of, most likely another config option.

**Comment by elengart** [comment]
Thanks Jackson!

**Comment by jackmarketon** [comment]
Hey @elengart, I've added a ignoreFiles config option in the `1.0.2` version. You can grab the branch if you want, otherwise it should be merged in and published by end of the week.

**Comment by elengart** [comment]
@jackmarketon - thank you for jumping on this so quickly!

**Comment by jackmarketon** [comment]
@elengart I've pushed this live to NPM now, a reinstall should grab v1.0.2
